import { displayRef } from "./state.mjs";
import { sha256, usage } from "./util.mjs";

export const TASK_FOLDER = "\\babysit\\";

/** A PowerShell single-quoted literal; nothing inside it is interpolated. */
export function quotePowerShell(value) {
  return `'${String(value).replace(/'/gu, "''")}'`;
}

/** A POSIX shell single-quoted word. */
export function quoteShell(value) {
  return `'${String(value).replace(/'/gu, "'\\''")}'`;
}

function slug(value) {
  return value.toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-+|-+$/gu, "").slice(0, 40) || "x";
}

export function taskNameFor(state) {
  return `babysit-${slug(state.pr.owner)}-${slug(state.pr.repo)}-${state.pr.number}-${sha256(state.prKey).slice(0, 8)}`;
}

/**
 * The commands that register and cancel a scheduled `tick`, for the agent to run itself. Nothing
 * here starts a schedule. Each run is one short `tick` that sends a T3 message only when there is news.
 */
export function scheduleCommands({ platform, execPath, helperPath, stateDir, statePath, state, intervalMinutes, env }) {
  const taskName = taskNameFor(state);
  const ref = displayRef(state.pr);
  const tickArgs = [helperPath, "tick", "--pr", ref, "--state-dir", stateDir];
  const logPath = statePath.replace(/\.json$/u, ".tick.log");

  if (platform === "win32") {
    const launcherPath = statePath.replace(/\.json$/u, ".tick.ps1");
    const launcher = [
      `# Generated by babysit schedule-command for ${ref}. Runs one tick, then exits.`,
      "$ErrorActionPreference = 'Continue'",
      `$node = ${quotePowerShell(execPath)}`,
      `$tickArgs = @(${tickArgs.map(quotePowerShell).join(", ")})`,
      `& $node @tickArgs *> ${quotePowerShell(logPath)}`,
      "exit $LASTEXITCODE",
      "",
    ].join("\r\n");
    const argument = `-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "${launcherPath}"`;
    const register = [
      "$scheduler = New-Object -ComObject 'Schedule.Service'",
      "$scheduler.Connect()",
      "try { $null = $scheduler.GetFolder('\\babysit') } catch { $null = $scheduler.GetFolder('\\').CreateFolder('babysit') }",
      `$action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument ${quotePowerShell(argument)}`,
      `$trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) -RepetitionInterval (New-TimeSpan -Minutes ${intervalMinutes})`,
      "$settings = New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 10) -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries",
      "$principal = New-ScheduledTaskPrincipal -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) -LogonType Interactive -RunLevel Limited",
      `Register-ScheduledTask -TaskPath ${quotePowerShell(TASK_FOLDER)} -TaskName ${quotePowerShell(taskName)} -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null`,
    ].join("\n");
    return {
      platform: "win32",
      shell: "powershell",
      taskName,
      watcherId: `${TASK_FOLDER}${taskName}`,
      intervalMinutes,
      launcher: { path: launcherPath, content: launcher },
      log: logPath,
      register,
      runNow: `Start-ScheduledTask -TaskPath ${quotePowerShell(TASK_FOLDER)} -TaskName ${quotePowerShell(taskName)}`,
      cancel: `Unregister-ScheduledTask -TaskPath ${quotePowerShell(TASK_FOLDER)} -TaskName ${quotePowerShell(taskName)} -Confirm:$false`,
      notes: [
        "The task runs as you with an interactive logon: only while you are signed in, because gh and T3 use your per-user credentials. Missed runs start when you sign in again.",
        "It starts powershell.exe with -WindowStyle Hidden and the launcher runs node in that hidden console. Windows can still show a console for an instant when the task starts.",
        "Each run is one tick: it reads GitHub, sends a T3 message only when there is news, and exits. A run that is still going when the next is due is skipped.",
        `The launcher keeps the last tick's output in ${logPath}.`,
      ],
    };
  }

  if (60 % intervalMinutes !== 0) throw usage("INVALID_INTERVAL", "cron intervals must divide 60 evenly: 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, or 60 minutes.");
  const schedule = intervalMinutes >= 60 ? "0 * * * *" : `*/${intervalMinutes} * * * *`;
  const marker = `# babysit:${taskName}`;
  const command = `${["env", `PATH=${env.PATH ?? "/usr/bin:/bin"}`, execPath, ...tickArgs].map(quoteShell).join(" ")} > ${quoteShell(logPath)} 2>&1`;
  // cron turns an unescaped % into a newline.
  const cronLine = `${schedule} ${command.replace(/%/gu, "\\%")} ${marker}`;
  return {
    platform,
    shell: "sh",
    taskName,
    watcherId: marker,
    intervalMinutes,
    launcher: null,
    log: logPath,
    cronLine,
    register: `(crontab -l 2>/dev/null | grep -vF ${quoteShell(marker)}; printf '%s\\n' ${quoteShell(cronLine)}) | crontab -`,
    runNow: command,
    cancel: `crontab -l 2>/dev/null | grep -vF ${quoteShell(marker)} | crontab -`,
    notes: [
      "cron runs the tick as you, with the PATH captured here so it can find gh. It needs your gh credentials to be readable without an interactive session.",
      "Each run is one tick: it reads GitHub, sends a T3 message only when there is news, and exits.",
      `The last tick's output is kept in ${logPath}.`,
    ],
  };
}
